name: Generate Profile Graphics

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * *" # Runs daily at 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate 3D contribution graph
      - name: Generate 3D Contrib Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Generate Snake Game
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push both sets of graphics in a single operation
      - name: Commit & Push Graphics
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "docs: auto-generate profile graphics (3D & Snake)" || exit 0
          git push
